apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: podinfo
  namespace: istio-system
spec:
  hosts: 
   - "*"
  http:
    - route:
       - destination:
           host: backend-podinfo.atit.svc.cluster.local
           port: 
            number: 9898
  gateways:
  - public-gateway