apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  targetNamespace: istio-system
  chart:
    spec:
      chart: grafana
      version: "6.4.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: istio-system
  interval: 5m
  values:
    sidecar:
      datasources:
        enabled: true
        label: mesh_datasource
      dashboards:
        enabled: true
        label: mesh_dashboard

    grafana.ini:
      auth:
        disable_login_form: true
        disable_signout_menu: true
      auth.anonymous:
        enabled: true
        org_role: Admin
        org_name: Main Org.
      auth.basic:
        enabled: false



    