apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
spec:
  releaseName: kiali-server
  targetNamespace: istio-system
  chart:
    spec:
      chart: kiali-server
      version: "1.30.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: istio-system
  interval: 5m
  values:
    auth:
      strategy: anonymous
    external_services:
      prometheus:
        url: http://prometheus-server:80
    
    