apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: istio-system
spec:
  releaseName: prometheus
  targetNamespace: istio-system
  chart:
    spec:
      chart: prometheus
      version: "13.4.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: istio-system
  interval: 5m
  values:
    server:
      global:
        scrape_interval: 10s
      
        