apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-loadtester
spec:
  releaseName: flagger-loadtester
  targetNamespace: flagger-test
  chart:
    spec:
      chart: loadtester
      version: ">=0.0.0"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: istio-system
  interval: 5m
    