apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: podinfo
  namespace: atit
spec:
  hosts: 
   - "backend-podinfo.atit"
  http:
    - route:
       - destination:
           host: backend-podinfo