apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  targetNamespace: istio-system
  chart:
    spec:
      chart: flagger
      version: ">=0.0.0"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: istio-system
  interval: 5m
  values:
    meshProvider: istio
    metricsServer: http://prometheus-server:80
    