apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
spec:
  interval: 5m
  releaseName: backend
  targetNamespace: atit-pinfobackend
  chart:
    spec:
      chart: podinfo
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: atit
        namespace: atit-pinfobackend
      interval: 1m
  install:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    service:
      enabled: false
    
